import fastity from 'fastify'
//CRIAR APP COM FRAMEWORK FASTITY. VARIAVEL CONSTANTE UTILIZANDO O FASTITY COMO UMA FUNCAO
const app = fastity()

//ROTA - QUANDO ALGUEM ACESSAR O ENDERECO /HELLO, QUERO QUE DEVOLVA "HELLO WORLD"
app.get('/hello', () => {
    return 'Hello World!'
})

//CRIAR API - PARA CRIAR UMA API PRECISA DE TER UM SERVIDOR HTTP. SERVIDOR HTTP É O ENDEREÇO ONDE O FRONT-END FAZ REQUISIÇÕES HTTP (GET , POST, DELETE...). AS REQUISIÇÕES VÃO PARA O SERVIDOR, QUE INTERPRETA ESSAS REQUISIÇÕES E DEVOLVE UMA RESPOSTA PARA ELAS.

//METODO LISTEN RECEBE UM OBJETO DE CONFIGURACOES E A CONFIGURACAO MAIS IMPORTANTE E OBRIGATORIA É A PORTA QUE QUERO EXECUTAR ESSE SERVIDOR (3333. 

//O LISTEN DEVOLVE UMA PROMISE, ISSO SIGNIFICA QUE ALGO PODE DEMORAR PARA ACONTECER/EXECUTAR. EM TODAS AS "PROMISE" PODE-SE CONCATENAR UM METODO "THEN()", QUE PERMITE NOS OUVIRMOS QUANDO TERMINAR

app.listen({
    port: 3333,
}).then(() => {
    console.log('🚀 HTTP server running on http://localhost:3333')
})

